# Generated by Django 4.1.3 on 2022-11-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workout_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.movement'),
        ),
    ]
