# Generated by Django 4.1.3 on 2022-11-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_exercise_reps_alter_exercise_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date of Workout'),
        ),
    ]
