# Generated by Django 4.1.3 on 2022-11-10 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_alter_exercise_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.movement'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='workout.workout'),
        ),
    ]
