# Generated by Django 4.1.3 on 2022-11-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_exercise_movement_alter_exercise_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateField(verbose_name='Date of Workout'),
        ),
    ]
